name: notify

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Run notify
        run: php notify.php
